import { SessionProvider, ThemeProvider } from '@/components/providers'
import { Toaster } from '@/components/ui/toaster'
import { TooltipProvider } from '@/components/ui/tooltip'
import { Footer, Navbar, Sidebar } from '@/layout'
import { config } from '@/utils/auth-config'
import { cn } from '@/utils/functions'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { Inter } from 'next/font/google'
import type { PropsWithChildren } from 'react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }: PropsWithChildren) {
	const session = await getServerSession(config)

	return (
		<html lang="en">
			<body
				className={cn('flex items-center w-full h-[100vh]', inter.className)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<TooltipProvider>
						<SessionProvider session={session}>
							<Sidebar />
							<main className="flex flex-auto flex-col items-center h-full">
								<Navbar />
								<section className="p-5 w-full h-full">{children}</section>
								<Footer />
							</main>
							<Toaster />
						</SessionProvider>
					</TooltipProvider>
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	)
}
